"use client";
import Image from "next/image";
import { Autoplay, EffectFade, Navigation, Pagination } from "swiper/modules";
import { Swiper, SwiperSlide } from "swiper/react";
import { ArrowRight, Phone } from "lucide-react";
import { Button } from "@/components/ui/button";
import type { HeroSlide } from "@/types";
import "swiper/css"; import "swiper/css/effect-fade"; import "swiper/css/navigation"; import "swiper/css/pagination";
export function Hero({ slides }: { slides: HeroSlide[] }) { const go = (id: string) => document.getElementById(id)?.scrollIntoView({ behavior: "smooth" }); return <section id="hero" className="relative overflow-hidden"><Swiper modules={[Autoplay, EffectFade, Navigation, Pagination]} effect="fade" loop autoplay={{ delay: 5500, disableOnInteraction: false }} navigation pagination={{ clickable: true }} className="hero-swiper h-[580px] sm:h-[650px]">{slides.map((slide) => <SwiperSlide key={slide.image}><div className="relative h-full"><Image src={slide.image} alt="HomeNet high-speed fiber network" fill priority={slide === slides[0]} sizes="100vw" className="object-cover"/><div className="absolute inset-0 bg-gradient-to-r from-[#061833]/95 via-[#071b3a]/72 to-[#071b3a]/30"/><div className="relative mx-auto flex h-full max-w-7xl items-center px-5 pb-10 sm:px-8"><div className="max-w-2xl text-white"><p className="mb-5 inline-flex rounded-full border border-white/20 bg-white/10 px-4 py-1.5 text-sm font-semibold backdrop-blur">{slide.eyebrow}</p><h1 className="max-w-xl text-4xl font-extrabold leading-[1.08] tracking-tight sm:text-6xl">{slide.title}</h1><p className="mt-6 max-w-lg text-base leading-7 text-blue-100 sm:text-lg">{slide.description}</p><div className="mt-9 flex flex-wrap gap-3"><Button size="lg" onClick={() => go("packages")}>View Packages <ArrowRight className="ml-2" size={18}/></Button><Button size="lg" variant="outline" onClick={() => go("contact")}><Phone className="mr-2" size={17}/> Contact Us</Button></div></div></div></div></SwiperSlide>)}</Swiper></section>; }
