"use client";

import { useState } from "react";
import Image from "next/image";
import { ArrowUpRight, Mail, Menu, Phone, X } from "lucide-react";

const links = [{ label: "Home", href: "/" }, { label: "Package", href: "/package" }, { label: "Offer", href: "/offer" }, { label: "Bill Pay", href: "/bill-pay" }, { label: "About Us", href: "/about-us" }, { label: "Contact Us", href: "/contact-us" }];

export function SiteHeader() {
  const [open, setOpen] = useState(false);
  return <header className="relative z-30"><div className="bg-navy text-white"><div className="mx-auto flex max-w-7xl flex-wrap items-center justify-between gap-x-6 gap-y-1 px-5 py-2 text-xs sm:px-8 sm:text-sm"><div className="flex items-center gap-4"><a href="mailto:support@homenet.com" className="flex items-center gap-1.5 hover:text-blue-200"><Mail size={14} /> support@homenet.com</a><a href="tel:+880100000000" className="flex items-center gap-1.5 hover:text-blue-200"><Phone size={14} /> +880 1XXX-XXXXXX</a></div><span className="font-medium text-blue-100">BTRC Approved Tariff</span></div></div><nav className="sticky top-0 border-b border-slate-100 bg-white/95 shadow-sm backdrop-blur"><div className="mx-auto flex h-[76px] max-w-7xl items-center justify-between px-5 sm:px-8"><a href="/" className="flex items-center gap-2.5 text-left" aria-label="Go to home"><span className="grid size-11 place-items-center overflow-hidden rounded-xl bg-white shadow-lg shadow-sky/15 ring-1 ring-slate-100"><Image src="/assets/fabiconlogo.png" alt="HomeNet logo" width={44} height={44} className="size-9 object-contain" priority /></span><span><span className="block text-xl font-extrabold tracking-tight text-ink">Home<span className="text-sky">Net</span></span><span className="block text-[9px] font-bold uppercase tracking-[.17em] text-slate-400">Internet service</span></span></a><div className="hidden items-center gap-7 lg:flex">{links.map((link) => <a key={link.label} href={link.href} className={link.label === "Bill Pay" ? "rounded-lg bg-ink px-4 py-2.5 text-sm font-semibold text-white hover:bg-sky" : "text-sm font-semibold text-slate-600 transition hover:text-sky"}>{link.label === "Bill Pay" && <ArrowUpRight className="mr-1 inline" size={14} />} {link.label}</a>)}</div><button className="grid size-10 place-items-center rounded-lg border border-slate-200 text-ink lg:hidden" onClick={() => setOpen(!open)} aria-label="Toggle menu">{open ? <X /> : <Menu />}</button></div>{open && <div className="border-t border-slate-100 bg-white px-5 py-4 shadow-lg lg:hidden">{links.map((link) => <a key={link.label} href={link.href} onClick={() => setOpen(false)} className="block w-full rounded-md px-3 py-3 text-left text-sm font-semibold text-slate-700 hover:bg-blue-50 hover:text-sky">{link.label}</a>)}</div>}</nav></header>;
}
